### ISSUE TITLE
pip install does not work [Mac]

### ISSUE THREAD

**Issue by jonathanbouchet** [THEGOLDENPRO/fastapi-tailwind#4]
Watch the YT video, it looks a pretty cool and useful package.
However I have some issues on Mac to install the package.

environment

- Python 3.11.8 (main, Mar 24 2024, 00:21:05) [Clang 11.0.3 (clang-1103.0.32.62)] on darwin
- fastapi: 0.112.2
- uvicorn:  0.30.6

When I tried the pip command, I got the following:

```py
pip install fastapi-tailwind
ERROR: Ignored the following yanked versions: 1.0.0.dev1
ERROR: Could not find a version that satisfies the requirement fastapi-tailwind (from versions: none)
ERROR: No matching distribution found for fastapi-tailwind
```

**Comment by THEGOLDENPRO** [comment]
Thank you for reporting, I think I just missed a MacOS wheel. Working on a fix very soon.

If you want a quick fix right now, you can git clone the repository and run `pip install .` in the root directory.

**Comment by THEGOLDENPRO** [comment]
Okay I just uploaded a release, try to see if this one works:
```sh
pip install fastapi-tailwind==1.0.1a6
```

**Comment by jonathanbouchet** [comment]
thanks.
I was able to pip install it but got the following error when reproducing the example:

```
ERROR:    Traceback (most recent call last):
  File "/Users/jonathanbouchet/Documents/WORK/FASTAPI_TAILWIND/venv/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanbouchet/Documents/WORK/FASTAPI_TAILWIND/main.py", line 13, in lifespan
    process = tailwind.compile(static_files.directory + "/output.css")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanbouchet/Documents/WORK/FASTAPI_TAILWIND/venv/lib/python3.11/site-packages/fastapi_tailwind/tailwind.py", line 90, in compile
    return Popen(args)
           ^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/jonathanbouchet/Documents/WORK/FASTAPI_TAILWIND/venv/lib/python3.11/site-packages/fastapi_tailwind/binaries/tailwindcss-macos-x64'
```

**Comment by THEGOLDENPRO** [comment]
> thanks. I was able to pip install it but got the following error when reproducing the example

thanks for catching that too, try the `alpha7` release:
```sh
pip install fastapi-tailwind==1.0.1a7
```

I think it's just that mac also requires the binary to be marked as an executable.

**Comment by jonathanbouchet** [comment]
`fastapi-tailwind==1.0.1a7` works, I can start the API.

I got these 2 warnings, not sure if relevant for you:
```
Rebuilding...
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
```

but the css file is generated in the `static` folder.

However when I use elements with tailwind classes, I do not the colors or shapes expected.

My html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>✨ Tailwind in 🔥 FastAPI</title>
    <link rel="stylesheet" href="/static/output.css">
</head>
    <body class="bg-slate-950">
        <h1 class="mt-10 text-center text-6xl font-bold text-red-400">👋 Hello ✨ Tailwind!</h1>

        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
        Button
        </button>
    </body>

</html>
```

<img width="821" alt="Screen Shot 2024-09-04 at 2 31 18 PM" src="https://github.com/user-attachments/assets/6db3736c-62af-40b3-8267-6b5dff53621c">

But I do see a difference in the html between when the css file is included or not, so that may just be that the `output.css` does not contain all classes, or it might be on my side.

**Comment by THEGOLDENPRO** [comment]
I think this is happening because you didn't tell tailwind where your source files are with the `content` config key. If you look at the example you'll know what I mean. https://github.com/THEGOLDENPRO/fastapi-tailwind/blob/main/examples/hello-world-app/tailwind.config.js

You can generate a tailwind.config.js file with this command:
```sh
fastapi-tailwind-init
```

**Comment by jonathanbouchet** [comment]
oh ... my bad.
with the `tailwind.config.js` file, I do not have the warnings mentioned above and the html elements have the proper colors.

So all good on Mac.

I can close the ticket.

**Comment by THEGOLDENPRO** [comment]
Once again thank you for bring these issues to light and have a great day. ⭐
